### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by bucko13**
General comments and questions:
- I wasn't sure if that was a typo or not in the Blind 1 Seed Phrase section since it was also in the screenshot (so presumably coming from the software), but it looked weird so I thought I'd edit just in case. Feel free to reject.

- I think it would be good to include potential downsides/foot guns somewhere, similar to the pros/cons list in the original [gist](https://gist.github.com/mflaxman/d72d25ad00941cea8241b6667cf008a8). Maybe even enumerate pros as well as cons here.

- Feel free to ignore this feedback or correct some misunderstanding I might be having since this could be totally subjective and narrow or me being wrong about something, but I felt a little confused by the name "blinded xpub". The initial image that it evokes in my head is that you're doing some kind of masking with the "passphrase" (i.e. the randomly generated path). What I imagined would happen with this mask is that you could apply it to a given account map to generate the _actual_ map. That doesn't seem to be what's going on though and instead it's more that the privacy protection is that the address is obscured by making it difficult to grind through the possible paths that would be associated with a given xpub. Once the account map is exposed though, all privacy benefits are lost. The only real difference from my using someone's xpub to generate a multisig and the blinded process is that the owner of the xpub would be less likely or able to guess what pubkeys that appear in the blockchain belong to it. Does this sound right? I'm not making a value judgement one way or the other, just trying to clarify in my head and also throw it out there in case there's a chance it could be confusing for others.
 
- One thing that I liked in the gist which didn't seem to be included here is the use of a passphrase to generate the path as opposed to just entropy (I could've missed it though. There are a couple mentions of a passphrase, but that seemed to be for encrypting the seed). I think that is a really nice feature of this proposal and imo should definitely be mentioned if you ever promote this to a BIP proposal. Benefits include: 
1) Many keystores already support passphrase entry even with limited input mechanisms. 
2) It's easy to grock for less technical users (e.g. "This passphrase generates the path needed for the account amp") 
3) It feels easier to backup and in some ways more secure since it can be stored in a way that's more ambiguous as to what it is. 
4) standardization will likely be needed for passphrase support around things like word list, capitalization, length, etc. 
5) As you mention, complexity is the enemy of security and it's pretty unlikely with a decent passphrase that this could be guessed. Making it easy to remember and convey feels more important and a bigger win

- Just spitballing here: an interesting way to add additional support in something like Caravan would be to have an extra field for a passphrase entry with an xpub that then generates the "blinded" xpub. So after you upload your xpub from a device or paste it in plain text, you'd have something like a checkbox that says: "blinded?", check it and then an input shows up that you enter the passphrase which generates the blinded path and resulting xpub which are used in the config/account map. To the point #5 above, we could even opt to not save that in the wallet config that is exported and so in order to load the watch only wallet, you have to know the blinding passphrase(s) and which key(s) they apply to.

### CODE REVIEW

**Comment by mflaxman** [comment]
Thanks for the PR/comments! Inline.

> General comments and questions:
> 
> * I wasn't sure if that was a typo or not in the Blind 1 Seed Phrase section since it was also in the screenshot (so presumably coming from the software), but it looked weird so I thought I'd edit just in case. Feel free to reject.

I think something funky happens with the display when you paste into python's `Cmd` module. I appreciate that your PR fixed it (at least in the text representation, the screenshot just strangely looks like that).

> * I think it would be good to include potential downsides/foot guns somewhere, similar to the pros/cons list in the original [gist](https://gist.github.com/mflaxman/d72d25ad00941cea8241b6667cf008a8). Maybe even enumerate pros as well as cons here.

I could do pros/cons, but I think it's better described vs passphrase use, so I added this section:
https://github.com/mflaxman/blind-xpub/#vs-passphrase

Is that good? The pros/cons were for an earlier version which mapped passphrase -> bip32 path. I think this construction is just better.

> * Feel free to ignore this feedback or correct some misunderstanding I might be having since this could be totally subjective and narrow or me being wrong about something, but I felt a little confused by the name "blinded xpub". The initial image that it evokes in my head is that you're doing some kind of masking with the "passphrase" (i.e. the randomly generated path). What I imagined would happen with this mask is that you could apply it to a given account map to generate the _actual_ map. That doesn't seem to be what's going on though and instead it's more that the privacy protection is that the address is obscured by making it difficult to grind through the possible paths that would be associated with a given xpub. Once the account map is exposed though, all privacy benefits are lost. The only real difference from my using someone's xpub to generate a multisig and the blinded process is that the owner of the xpub would be less likely or able to guess what pubkeys that appear in the blockchain belong to it. Does this sound right?

I wouldn't say "less likely." It goes from "easy" if you have tech savvy (and I'd imagine one day this will be a feature you could search in a block explorer) to impossible no matter how savvy you are.

I'm not making a value judgement one way or the other, just trying to clarify in my head and also throw it out there in case there's a chance it could be confusing for others.

How can I phrase it better?

I added this section (previously from a sub-document) to the top to explain what the whole goal is and I think this helps a lot.
https://github.com/mflaxman/blind-xpub/#privacy-leakage

> * One thing that I liked in the gist which didn't seem to be included here is the use of a passphrase to generate the path as opposed to just entropy (I could've missed it though. There are a couple mentions of a passphrase, but that seemed to be for encrypting the seed). I think that is a really nice feature of this proposal and imo should definitely be mentioned if you ever promote this to a BIP proposal. Benefits include:
> 
> 1. Many keystores already support passphrase entry even with limited input mechanisms.
> 2. It's easy to grock for less technical users (e.g. "This passphrase generates the path needed for the account amp")
> 3. It feels easier to backup and in some ways more secure since it can be stored in a way that's more ambiguous as to what it is.
> 4. standardization will likely be needed for passphrase support around things like word list, capitalization, length, etc.
> 5. As you mention, complexity is the enemy of security and it's pretty unlikely with a decent passphrase that this could be guessed. Making it easy to remember and convey feels more important and a bigger win
> 
> * Just spitballing here: an interesting way to add additional support in something like Caravan would be to have an extra field for a passphrase entry with an xpub that then generates the "blinded" xpub. So after you upload your xpub from a device or paste it in plain text, you'd have something like a checkbox that says: "blinded?", check it and then an input shows up that you enter the passphrase which generates the blinded path and resulting xpub which are used in the config/account map. To the point #5 above, we could even opt to not save that in the wallet config that is exported and so in order to load the watch only wallet, you have to know the blinding passphrase(s) and which key(s) they apply to.

I think the passphrase is strictly inferior to the blinded path, and I explicitly moved away from that in this version of the protocol (I no longer have a way for a user to enter a passphrase and generate a bip32 path for example). I added this section for discussion:
https://github.com/mflaxman/blind-xpub/#vs-passphrase

Do you agree/disagree?

**Comment by bucko13** [comment]
> I wouldn't say "less likely." It goes from "easy" if you have tech savvy (and I'd imagine one day this will be a feature you could search in a block explorer) to impossible no matter how savvy you are.

Yeah, fair. Impossible :) 

How would this be searchable in a block explorer though?? Are you talking about if it's blinded vs not blinded? Even then, how are paths exposed on a block explorer? 

> How can I phrase it better?
I added this section (previously from a sub-document) to the top to explain what the whole goal is and I think this helps a lot.
https://github.com/mflaxman/blind-xpub/#privacy-leakage

Yeah, it definitely helps understand it, and I had read that too I think. It's less about the explanation and more just about the name. It feels less like a blinded xpub, which just sounds like it implies a mask that reveals something if unmasked, and more of a "secret" xpub. I could also see why it makes sense in that the actual xpub used is "blinded" by the random path generated. Anyway, like I said, mainly just thinking out loud. Definitely wouldn't be a blocker for me!

Maybe all this needs is a "What are blinded xpubs" section at the top. You kind of have a lot of "why", but a simple "what" to kick things off after the abstract might go a long way.

>  could do pros/cons, but I think it's better described vs passphrase use, so I added this section:
So for pros/cons, I'm thinking more of comparing using this proposal to not using blinded at all. The most obvious example of a con is something you hint at but I think is best made explicit in a pros/cons list: complexity can be the enemy of security. You really have these throughout the whole post, but I think a list or a "why you might not want to use this" would be good. 

I'm not really sure how the passphrase section is really applicable anyway. The passphrase is applied to the seed to basically generate a new seed right? From there you generate the xpub, which, if it's from a regular path, exposes information to any holder of it. I could just be missing context but passphrases feel like they solve a different issue (and I agree that esp. in multisig they might do more harm than good)

Clarification on something fromm the passphrase section:
> (they choose to restrict paths to simplify the UI).

This isn't strictly true, at least this isn't the reason from my understanding. The reason they restrict it is precisely due to the footguns that would be useful to put in a pros/cons list. The HWW manufacturers have had to deal with customers who sent to paths they didn't know how to recover from. I believe we've had to do this at unchained as well (to help recover funds that they wanted to store with UC). I think this is important to note especially since it represents a bigger road block to adoption than just being a UI simplification 

> Do you agree/disagree?

So maybe I wasn't explaining myself well with the passphrase. I could also be confused because I haven't been following all the conversations super closely. The way I was talking about a passphrase wasn't for "unlocking" the HWW at all, but rather as an alternative mechanism to generate the "long unpredictable BIP32 path". The hardware doesn't even have to be aware of this passphrase if you don't want. I think you even had it working this way in your original demo.

What I'm thinking wouldn't pre-empt anything that's described in your protocol, but rather saying maybe there could be some specification for how to generate the random path deterministically from a random passphrase. Once it's generated, you can store the account map as is w/ the secret path and then all of the advantages for paths still apply. Or you could store the account map w/o the path and require the passphrase to get the _actual_ path. 

Again, it's possible I'm misunderstanding something, but if not, I do think that having the option to store the secret path as a passphrase has the advantages that I listed previously of convenience and obfuscation. 

It seems to me that even a weak passphrase used to generate a hidden path would be strictly superior to the status quo, especially if you can store the "blinded" account map (i.e. w/o the hidden paths) and the passphrase used to generate the hidden path separately. The choice isn't between weak blinded xpub or strong blinded xpub, for some it might be a choice between no blinded xpub and a weak one. 

Another thought -> If it was using the BIP39 seed word list then it could also be generated with dice (or whatever) and you wouldn't have to rely on software to generate the randomness for you. Compare the resulting secret path generated from that passphrase in different software implementations and you can guarantee it's secure and random.

Most of the comments in the "vs. passphrase" section don't feel like they apply to the way I was thinking about it but hopefully the above makes it a little more clear what I meant.

**Comment by mflaxman** [comment]
> > I wouldn't say "less likely." It goes from "easy" if you have tech savvy (and I'd imagine one day this will be a feature you could search in a block explorer) to impossible no matter how savvy you are.
> 
> Yeah, fair. Impossible :)
> 
> How would this be searchable in a block explorer though?? Are you talking about if it's blinded vs not blinded? Even then, how are paths exposed on a block explorer?

With standard/unblinded paths, it'd work like this:
1. A bad actor (or nosy heir/accountant/lawyer) gets unauthorized access to a BIP39 seed (and passphrase, if applicable). Through curiosity or government order they decide to snoop at what they've got.
2. They enter that seed (& passphrase) into a block explorer, or more likely for security the corresponding hardened child xpub (along the standard path).
3. The block explorer has every pubkey ever used in a redeem script indexed and it queries against both change/receiving branches, perhaps with a gap limit of ~20.
4. Voila! You have a history of every spent TX that this seed phrase could have cosigned on, and you can do some forensic analysis of change to determine what it might be HODLing (and you already know the very likely threshold).

Currently, this feature doesn't exist, but there's no reason it couldn't be implemented if there was demand. I wrote a similar hidden easter egg feature in blockcypher's block explorer in 2015, and I know blockchain.info had an xpub search feature at the time.

It'd be trivial for me to release a short script that would do this against your own bitcoin core full node, though the rescan would be very slow.

> 
> > How can I phrase it better?
> > I added this section (previously from a sub-document) to the top to explain what the whole goal is and I think this helps a lot.
> > https://github.com/mflaxman/blind-xpub/#privacy-leakage
> 
> Yeah, it definitely helps understand it, and I had read that too I think. It's less about the explanation and more just about the name. It feels less like a blinded xpub, which just sounds like it implies a mask that reveals something if unmasked, and more of a "secret" xpub. I could also see why it makes sense in that the actual xpub used is "blinded" by the random path generated. Anyway, like I said, mainly just thinking out loud. Definitely wouldn't be a blocker for me!
> 
> Maybe all this needs is a "What are blinded xpubs" section at the top. You kind of have a lot of "why", but a simple "what" to kick things off after the abstract might go a long way.

Does this help?

Sorry, I can't remember if it was in the last iteration you saw:
https://github.com/mflaxman/blind-xpub/#solution

> 
> > could do pros/cons, but I think it's better described vs passphrase use, so I added this section:
> 
> So for pros/cons, I'm thinking more of comparing using this proposal to not using blinded at all. The most obvious example of a con is something you hint at but I think is best made explicit in a pros/cons list: complexity can be the enemy of security. You really have these throughout the whole post, but I think a list or a "why you might not want to use this" would be good.

Added:
https://github.com/mflaxman/blind-xpub/#versus-regular-unblinded-seeds

> 
> I'm not really sure how the passphrase section is really applicable anyway. The passphrase is applied to the seed to basically generate a new seed right? From there you generate the xpub, which, if it's from a regular path, exposes information to any holder of it. I could just be missing context but passphrases feel like they solve a different issue (and I agree that esp. in multisig they might do more harm than good)

I'm talking about [this competing proposal](https://github.com/BlockchainCommons/Airgapped-Wallet-Community/discussions/37). I just updated this section to try and make that a little more clear.

> 
> Clarification on something from the passphrase section:
> 
> > (they choose to restrict paths to simplify the UI).
> 
> This isn't strictly true, at least this isn't the reason from my understanding. The reason they restrict it is precisely due to the footguns that would be useful to put in a pros/cons list. The HWW manufacturers have had to deal with customers who sent to paths they didn't know how to recover from. I believe we've had to do this at unchained as well (to help recover funds that they wanted to store with UC). I think this is important to note especially since it represents a bigger road block to adoption than just being a UI simplification

I don't think that's the case with multisig as you already need to backup your output descriptors as part of your setup. If you do that, it doesn't matter what paths you choose. But if you don't backup your output descriptors (very dangerous, especially for larger multisigs like 4-of-7) then it is a factor.

Added that here:
https://github.com/mflaxman/blind-xpub/#regular-unblinded-seed-advantages


> 
> > Do you agree/disagree?
> 
> So maybe I wasn't explaining myself well with the passphrase. I could also be confused because I haven't been following all the conversations super closely. The way I was talking about a passphrase wasn't for "unlocking" the HWW at all, but rather as an alternative mechanism to generate the "long unpredictable BIP32 path". The hardware doesn't even have to be aware of this passphrase if you don't want. I think you even had it working this way in your original demo.

What's the use-case for knowing a single HWWs bip32 path but not the full account map? I can't think of any.

I think the fact that my previous proposal used a passphrase -> bip32 path scheme is what's making this confusing. The current iteration doesn't mention this.

> 
> What I'm thinking wouldn't pre-empt anything that's described in your protocol, but rather saying maybe there could be some specification for how to generate the random path deterministically from a random passphrase. Once it's generated, you can store the account map as is w/ the secret path and then all of the advantages for paths still apply. Or you could store the account map w/o the path and require the passphrase to get the _actual_ path.
> 
> Again, it's possible I'm misunderstanding something, but if not, I do think that having the option to store the secret path as a passphrase has the advantages that I listed previously of convenience and obfuscation.
> 
> It seems to me that even a weak passphrase used to generate a hidden path would be strictly superior to the status quo, especially if you can store the "blinded" account map (i.e. w/o the hidden paths) and the passphrase used to generate the hidden path separately. The choice isn't between weak blinded xpub or strong blinded xpub, for some it might be a choice between no blinded xpub and a weak one.
> 
> Another thought -> If it was using the BIP39 seed word list then it could also be generated with dice (or whatever) and you wouldn't have to rely on software to generate the randomness for you. Compare the resulting secret path generated from that passphrase in different software implementations and you can guarantee it's secure and random.

Ya, other ways to generate the bip32 path (including the HWW itself), would make sense. But since the only risk is privacy (not explicitly security) I'm fine to trust the RNG. When it comes to tinfoil hat protection, YMMV :)
> 
> Most of the comments in the "vs. passphrase" section don't feel like they apply to the way I was thinking about it but hopefully the above makes it a little more clear what I meant.

Is it better now that it's reworked on "versus passphrase" and "versus regular (unblinded)"?

**Comment by bucko13** [comment]
> With standard/unblinded paths, it'd work like this:

gotcha! Makes sense. I thought you were implying that the paths could be inferred from a block explorer or something. I think adding this to a block explorer (maybe one of the open source ones you can run on your own node like [btc-rpc-explorer](https://github.com/janoside/btc-rpc-explorer) would be a great way to make the case for this. 

>Does this help?
Sorry, I can't remember if it was in the last iteration you saw:
https://github.com/mflaxman/blind-xpub/#solution

Yes, except for this: 

> "we demonstrate using a large and randomly generated BIP32 path to blind a BIP39 seed (or more specifically the corresponding xpub) in a multisig quorum." 

It feels less like blinding the seed and more like creating a firewall between the seed (specifically its owner) and knowing the xpub that is used in the multisig forum. Maybe that's what you mean by blinding though and I'm just getting hung up on something that most others won't. Thinking of it like a firewall helps me though, making it hard to get from xpub at path /f/o/o to xpub at path /b/a/r. Anyway, this is just a subjective thing, feel free to ignore.

> Vs. Other protocols.

I like this section. I would recommend avoiding adding counter points to the protocols you don't personally support/like. I get what you're doing, but it feels distracting. Add those points to the Pros supporting blinded and let it stand on its own. 

I would personally leave the vs passphrases out of it. The way that proposal reads is confusing to begin with. I don't like it, it's unnecessarily complicated (all of them need a passphrase and they're stored with the account map? why?), and it's not adopted anywhere as far as I'm aware. I think it muddies your proposal by including it in your own proposal. 

>>> (they choose to restrict paths to simplify the UI).
>
>>This isn't strictly true, at least this isn't the reason from my understanding. The reason they restrict it is precisely due to the footguns that would be useful to put in a pros/cons list. The HWW manufacturers have had to deal with customers who sent to paths they didn't know how to recover from. I believe we've had to do this at unchained as well (to help recover funds that they wanted to store with UC). I think this is important to note especially since it represents a bigger road block to adoption than just being a UI simplification
>
> I don't think that's the case with multisig as you already need to backup your output descriptors as part of your setup. If you do that, it doesn't matter what paths you choose. But if you don't backup your output descriptors (very dangerous, especially for larger multisigs like 4-of-7) then it is a factor.

I think we're maybe talking past each other on this point. I'm just responding to your comment that they restrict paths to simplify the UI. Whether its true or not with multisig is kind of besides the point. The reasons they give for having path restrictions isn't a simpler UI but to stop people from making mistakes, arguing against anyone that is using different paths that they should just use the standard they've adopted. 

> I think the fact that my previous proposal used a passphrase -> bip32 path scheme is what's making this confusing. The current iteration doesn't mention this.

Honestly, I'd forgotten the previous iteration of the proposal, and I was finding myself a little lost here. Going back to the original proposal actually helped clarify it in my mind. 

> What's the use-case for knowing a single HWWs bip32 path but not the full account map? I can't think of any.

It seems to me that there's an advantage of being able to store the path and the account map separately. Now, if your account map is compromised your wallet is still private as long as they don't have the passphrase to generate one or more blinded paths/xpubs. It's also easier to memorize a passphrase than to memorize a random path (if you were so inclined). It also feels useful to me that you can upload an account map to something like caravan, then input a passphrase that alters the path(s) of that account map to generate the _actual_ account map. Now, there's even less risk to storing your account map somewhere semi-public. I could share my account map on twitter, where I (or my heirs) could retrieve it later, but the passphrase is kept in a safety deposit box. 

I definitely agree it's not a need to have. But it seems like a nice to have. 

> But since the only risk is privacy (not explicitly security) I'm fine to trust the RNG.

Fair point about only risk being privacy. To be clear though, I'm not talking about trusting the RNG, but rather the developer who used it in their library. The demo you shared has a very straightforward UI for getting the random path. Now, as someone who is relatively tech-savvy, I realize that I want to make sure that that path isn't being generated in a way you can later guess, i.e. you're actually using a RNG to generate it. Luckily I know how to look at the code and see you're using something native to python. Someone who is less comfortable with looking at code couldn't do that. Something may look random to the user without actually being random. If I have a random passphrase though, I can confirm in two different pieces of software that the passphrase is always generating to the same random path. 

All that said, you're totally right privacy is the only thing at risk here, so way less of a big deal than if we were talking about security.

**Comment by mflaxman** [comment]
Thanks! Inline.

> > With standard/unblinded paths, it'd work like this:
> 
> gotcha! Makes sense. I thought you were implying that the paths could be inferred from a block explorer or something. I think adding this to a block explorer (maybe one of the open source ones you can run on your own node like [btc-rpc-explorer](https://github.com/janoside/btc-rpc-explorer) would be a great way to make the case for this.
> 
> > Does this help?
> > Sorry, I can't remember if it was in the last iteration you saw:
> > https://github.com/mflaxman/blind-xpub/#solution
> 
> Yes, except for this:
> 
> > "we demonstrate using a large and randomly generated BIP32 path to blind a BIP39 seed (or more specifically the corresponding xpub) in a multisig quorum."
> 
> It feels less like blinding the seed and more like creating a firewall between the seed (specifically its owner) and knowing the xpub that is used in the multisig forum. Maybe that's what you mean by blinding though and I'm just getting hung up on something that most others won't. Thinking of it like a firewall helps me though, making it hard to get from xpub at path /f/o/o to xpub at path /b/a/r. Anyway, this is just a subjective thing, feel free to ignore.

Hmmm, maybe I need a better word. In my mind I think of it as blinding, maybe masking is better? I think blinding is the most accurate, especially since blinding protocols already have the idea of unblinding built in.

> 
> > Vs. Other protocols.
> 
> I like this section. I would recommend avoiding adding counter points to the protocols you don't personally support/like. I get what you're doing, but it feels distracting. Add those points to the Pros supporting blinded and let it stand on its own.
> 
> I would personally leave the vs passphrases out of it. The way that proposal reads is confusing to begin with. I don't like it, it's unnecessarily complicated (all of them need a passphrase and they're stored with the account map? why?), and it's not adopted anywhere as far as I'm aware. I think it muddies your proposal by including it in your own proposal.

Hmmm, I can see all of that. Someone else gave feedback suggesting I add that section.

> 
> > > > (they choose to restrict paths to simplify the UI).
> > 
> > 
> > > This isn't strictly true, at least this isn't the reason from my understanding. The reason they restrict it is precisely due to the footguns that would be useful to put in a pros/cons list. The HWW manufacturers have had to deal with customers who sent to paths they didn't know how to recover from. I believe we've had to do this at unchained as well (to help recover funds that they wanted to store with UC). I think this is important to note especially since it represents a bigger road block to adoption than just being a UI simplification
> > 
> > 
> > I don't think that's the case with multisig as you already need to backup your output descriptors as part of your setup. If you do that, it doesn't matter what paths you choose. But if you don't backup your output descriptors (very dangerous, especially for larger multisigs like 4-of-7) then it is a factor.
> 
> I think we're maybe talking past each other on this point. I'm just responding to your comment that they restrict paths to simplify the UI. Whether its true or not with multisig is kind of besides the point. The reasons they give for having path restrictions isn't a simpler UI but to stop people from making mistakes, arguing against anyone that is using different paths that they should just use the standard they've adopted.

I have a new tweak on this (proposed by another reviewer) to make the random bip32 paths deterministic from xpubs such that recovery of all n seeds is enough to recover all bip32 paths (even if the output descriptors are lost). I'm going to update to that. Test code here IYC:
https://github.com/mflaxman/blind-xpub/blob/deterministic-paths/deterministic_paths.py

> 
> > I think the fact that my previous proposal used a passphrase -> bip32 path scheme is what's making this confusing. The current iteration doesn't mention this.
> 
> Honestly, I'd forgotten the previous iteration of the proposal, and I was finding myself a little lost here. Going back to the original proposal actually helped clarify it in my mind.
> 
> > What's the use-case for knowing a single HWWs bip32 path but not the full account map? I can't think of any.
> 
> It seems to me that there's an advantage of being able to store the path and the account map separately. Now, if your account map is compromised your wallet is still private as long as they don't have the passphrase to generate one or more blinded paths/xpubs. It's also easier to memorize a passphrase than to memorize a random path (if you were so inclined). It also feels useful to me that you can upload an account map to something like caravan, then input a passphrase that alters the path(s) of that account map to generate the _actual_ account map. Now, there's even less risk to storing your account map somewhere semi-public. I could share my account map on twitter, where I (or my heirs) could retrieve it later, but the passphrase is kept in a safety deposit box.
> 
> I definitely agree it's not a need to have. But it seems like a nice to have.

Hmmm, I do like that you could even have multiple multisig passphrases -> multiple multisig wallets. The decoy wallet might have ~10% of your HODL (similar to bip39 deniability). I'm just not sure the extra complexity is really worth it here. I think of passphrases as "super secure private key material that you must memorize forever and never leak and if you get something wrong catastrophic things can happen." Whereas bip32 paths are privacy-related info; still very important but more concerned with loss vs theft.

Put differently, the more complicated the system the fewer the people will use it (and the more will get it wrong). 99% of users I'd expect wouldn't use plausibly deniable multisig passphrases. That said, it would be pretty easy to add.

> 
> > But since the only risk is privacy (not explicitly security) I'm fine to trust the RNG.
> 
> Fair point about only risk being privacy. To be clear though, I'm not talking about trusting the RNG, but rather the developer who used it in their library. The demo you shared has a very straightforward UI for getting the random path. Now, as someone who is relatively tech-savvy, I realize that I want to make sure that that path isn't being generated in a way you can later guess, i.e. you're actually using a RNG to generate it. Luckily I know how to look at the code and see you're using something native to python. Someone who is less comfortable with looking at code couldn't do that. Something may look random to the user without actually being random. If I have a random passphrase though, I can confirm in two different pieces of software that the passphrase is always generating to the same random path.

Hard for me to be against this, I think I was the one who coined the phrase "don't trust the random number generator, be the random number generator."

However, my new tweak in randomness generation (see branch linked earlier) solves this problem. Instead, we move to a deterministic PRF that mimics a CSPRNG. Put simply: you can verify it trivially on another device.

> 
> All that said, you're totally right privacy is the only thing at risk here, so way less of a big deal than if we were talking about security.

**Pull request merged**
